Add unknown icon code
andrebrait/prime-indicator pull request #28
Opened 2017-11-10 01:59 UTC by Aaahh

I was debating whether or not to add it to 76-94 but I stuck with what I did instead
SVGs are still needed

2017-11-10 04:00 UTC, andrebrait requested changes
The code seems good, but I can't merge until the SVGs are present. I'm afraid I can't take a look into it until December, at best.

2018-04-15 15:36 UTC, Aaahh commented
https://github.com/luzfcb/prime-indicator/commit/ac5084da9089765f3927b93b1126827a95a45ef3

2018-04-15 15:56 UTC, andrebrait commented
Ok, good. I'll see when I can review this again and merge. Thanks for the image!

2018-04-16 11:16 UTC, andrebrait approved these changes

2018-04-16 11:18 UTC, merged